version: 2

formats: all

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - python3-gi
    - python3-dbus
    - python3-pyudev
    - python3-setuptools
