version: 2

formats: all

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - libcairo2-dev
    - libffi-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libdbus-1-dev
    - python3-cairo-dev
