name: pemmican-test-suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            python: "3.9"
            experimental: false
          - os: ubuntu-22.04
            python: "3.10"
            experimental: false
          - os: ubuntu-22.04
            python: "3.11"
            experimental: false
          - os: ubuntu-22.04
            python: "3.12"
            experimental: false

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Checkout pemmican
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt install -y libglib2.0-dev libdbus-1-dev
          sudo apt build-dep -y python3-gi
          make develop

      - name: Run tests
        run: |
          make test
